### ISSUE TITLE
Long Wait for Response on PGDP5K Dataset Application

### ISSUE THREAD

**Issue by BestJob2000** [mingliangzhang2018/PGDP#7]
I applied for the PGDP5K dataset as instructed a while ago, but I have not received any response yet. Is there anyway to get an update on the status of my application? Or could you please provide another way to get the dataset？Thank you.

**Comment by mingliangzhang2018** [comment]
I'm sorry that the I can't see the application because the specified email address is invalid. 
We decided to make this dataset public and no longer require an application. 
The keywords for PGDP5K dataset is 'pal_2022'.

**Comment by BestJob2000** [comment]
Thank you!

**Comment by VietDunghacker** [comment]
Hi, I downloaded the dataset from the website but I cannot unzip the file with your password. Is the password correct?

**Comment by mingliangzhang2018** [comment]
> Hi, I downloaded the dataset from the website but I cannot unzip the file with your password. Is the password correct?

Please try again with new password.
