### ISSUE TITLE
Not all images in Geometry3K are in name_pairs.txt

### ISSUE THREAD

**Issue by BestJob2000** [mingliangzhang2018/PGDP#8]
Hi,
I am currently trying to perform inference on the Geometry3K dataset to generate logic forms. The test set in Geometry3K ranges from 2401 to 3001. However, I noticed that some images are missing in the name_pairs.txt file, such as 2401, 2403, 2408, 2409, and many others. Did I make a mistake somewhere? 
Thank you!
![image](https://github.com/user-attachments/assets/595a635d-77e5-420c-a65b-4638ec93937c)

**Comment by mingliangzhang2018** [comment]
We remove all duplicated samples in Geometry3K. If you want to get all samples from 2401 to 3001, you could obtain from  other sample annotation according to images in PGDP5K.

**Comment by BestJob2000** [comment]
Thank you for your reply. But how can I find the actual corresponding samples for Geometry3K test set?

**Comment by mingliangzhang2018** [comment]
according to image, the same images have the same annotaion

**Comment by BestJob2000** [comment]
Thank you! I counted the number of duplicate images in the Geometry3K, and extended the name_pairs.txt file so that everyone can find the direct pair relations for each image in the Geometry3K dataset.
[new_name_pairs.txt](https://github.com/user-attachments/files/17675805/new_name_pairs.txt)

**Comment by mingliangzhang2018** [comment]
Thanks a lot!
